import hashlib
import json
import logging
import random
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from functools import lru_cache
from pathlib import Path

from deep_translator import GoogleTranslator
from deep_translator.exceptions import RequestError, TooManyRequests, TranslationNotFound
from groq import Groq

from app.config import settings
from app.services.text_clean import strip_decorative_symbols

logger = logging.getLogger(__name__)

_client = Groq(api_key=settings.groq_api_key)

_LANG_NAME = {"en": "English", "hi": "Hindi (Devanagari script)"}

# Language codes for deep-translator's GoogleTranslator (the free web-scraping
# endpoint, no API key) - separate from _LANG_NAME above, which is only used
# to build Groq prompts for the Q&A/summarize/suggested-questions functions
# further down. Translation itself no longer goes through Groq at all: no
# reasoning-token budget to run out, no per-minute LLM rate limit, no JSON
# parsing of a model's output. Trade-off: this hits Google's unofficial
# translate.google.com endpoint, which has its own (undocumented) rate
# limiting and can occasionally 429/error under heavy concurrent load - see
# _translate_chunk's retry handling below.
_DT_LANG = {"en": "en", "hi": "hi"}

# Process-local cache: many different students hit "read module 2 in
# Hindi" / "summarize this" / etc. for the exact same content, and none
# of that changes between requests, so caching by the call's own inputs
# skips a repeat Groq call (and its cost + latency) entirely on a hit.
# Caveats worth knowing:
#   - It's in-memory per worker process - resets on restart/redeploy, and
#     isn't shared across multiple uvicorn/gunicorn workers if you run more
#     than one. Fine for a single-process dev/staging setup like this one;
#     swap for Redis (or similar) behind the same function signatures if
#     you scale to multiple workers.
#   - It does NOT know when course content changes upstream - if a module's
#     text is edited on the Rozzgaar side, a stale cached translation/
#     summary can keep being served until this process restarts. Bump
#     _CACHE_MAXSIZE's neighboring functions' cache with .cache_clear()
#     (e.g. from an admin endpoint or content-refresh hook) if that's a
#     concern for you.
_CACHE_MAXSIZE = 256

# --------------------------------------------------------------------------
# Disk-backed cache for course-content summaries and suggested questions.
#
# The lru_cache above only survives for the life of one worker process - on
# every restart/redeploy it's empty again, so the FIRST student to open a
# given course after a deploy re-triggers a Groq summarize() /
# generate_suggested_questions() call for content that hasn't actually
# changed. Since these two are keyed off a whole course/module's text (not
# a live per-user question), they're exactly the case worth persisting: the
# same course's summary/suggested-questions should be generated by Groq
# ONCE, ever, not once per deploy. Keyed by content hash + params (mirrors
# app/services/video_transcript.py's cache pattern), so it stays correct
# automatically if the underlying text changes (new key -> cache miss ->
# regenerate) and stale entries just sit unused rather than serving wrong
# content.
# --------------------------------------------------------------------------
_RESPONSE_CACHE_LOCK = threading.Lock()


def _response_cache_path() -> Path:
    p = Path(settings.data_dir) / "llm_response_cache.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def _load_response_cache() -> dict:
    path = _response_cache_path()
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("LLM response cache unreadable (%s), starting fresh.", exc)
        return {}


def _save_response_cache(cache: dict) -> None:
    try:
        _response_cache_path().write_text(json.dumps(cache, ensure_ascii=False), encoding="utf-8")
    except OSError as exc:
        logger.warning("Failed to persist LLM response cache: %s", exc)


def _response_cache_key(namespace: str, *parts: object) -> str:
    raw = namespace + "\x1f" + "\x1f".join(repr(p) for p in parts)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _disk_cached(namespace: str, key_parts: tuple, compute):
    """Return the cached value for (namespace, key_parts) if present on
    disk, otherwise call compute(), persist the result, and return it.
    Safe across threads (single lock around read-modify-write); not
    multi-process safe under concurrent writes to the SAME key, but a
    duplicate Groq call in that narrow race is harmless - it just means
    one of the two write attempts is what ends up persisted."""
    key = _response_cache_key(namespace, *key_parts)
    with _RESPONSE_CACHE_LOCK:
        cache = _load_response_cache()
        if key in cache:
            return cache[key]
    result = compute()
    with _RESPONSE_CACHE_LOCK:
        cache = _load_response_cache()
        cache[key] = result
        _save_response_cache(cache)
    return result


def _complete(system: str, user: str, temperature: float = 0.3, max_tokens: int = 700,
              reasoning_effort: str | None = "low") -> str:
    # groq_model (openai/gpt-oss-20b) is a reasoning model: hidden "thinking"
    # tokens are drawn from the SAME max_tokens budget as the visible answer.
    # On bigger prompts (e.g. a large translate-batch chunk) the model can
    # spend the whole budget reasoning and return an EMPTY message - which
    # then fails JSON parsing downstream. reasoning_effort="low" keeps most
    # of the budget available for actual output on tasks (like translation)
    # that don't need deep reasoning. Only gpt-oss/qwen3 models on Groq
    # accept this param, so skip it silently for anything else.
    # NOTE: this now DEFAULTS to "low" (previously every call site left it
    # at None, so the flag documented above was never actually sent to
    # Groq - the empty-response warnings in the logs were exactly this).
    # Pass reasoning_effort=None explicitly to opt a call out.
    kwargs = {}
    if reasoning_effort and "gpt-oss" in settings.groq_model:
        kwargs["reasoning_effort"] = reasoning_effort
    resp = _client.chat.completions.create(
        model=settings.groq_model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
        **kwargs,
    )
    content = resp.choices[0].message.content
    finish_reason = resp.choices[0].finish_reason
    if (not content or not content.strip()) and finish_reason == "length":
        # Even with reasoning_effort="low", a big enough prompt can still
        # eat the whole budget on hidden reasoning tokens. One retry with a
        # meaningfully larger budget clears almost all of these rather than
        # silently returning "" to the caller (which upstream turns into a
        # visible failure - a blank summary, an empty suggested-question
        # list, an unanswered chat message).
        retry_tokens = max_tokens * 2
        logger.warning("Groq returned empty content (finish_reason=length, max_tokens=%d) - "
                        "retrying once with max_tokens=%d.", max_tokens, retry_tokens)
        resp = _client.chat.completions.create(
            model=settings.groq_model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=temperature,
            max_tokens=retry_tokens,
            **kwargs,
        )
        content = resp.choices[0].message.content
        finish_reason = resp.choices[0].finish_reason
        if not content or not content.strip():
            logger.warning("Groq still returned empty content after retry (finish_reason=%s, "
                            "max_tokens=%d).", finish_reason, retry_tokens)
    return (content or "").strip()


@lru_cache(maxsize=_CACHE_MAXSIZE)
def _cached_answer(question: str, context_chunks: tuple[str, ...], language: str) -> str:
    lang_name = _LANG_NAME.get(language, "English")
    context = "\n\n---\n\n".join(context_chunks) if context_chunks else "No matching content was found."
    system = (
        "You are the official assistant for Rozzgaar (rozzgaar.in), a skills training and "
        "certification platform. Answer ONLY using the CONTEXT provided - never invent course "
        "names, prices, or policies.\n\n"
        "The CONTEXT is the course/page the user is currently browsing (plus closely related "
        "material). If the CONTEXT contains the answer - even if it's covered under a specific "
        "module/chapter - answer the question directly and completely right here using that "
        "content. Do NOT tell the user to go open a module, section, or page for information "
        "that's already sitting in the CONTEXT; that just makes them do the reading themselves. "
        "Only mention a module/chapter by name if the user asks where something is covered, not "
        "as a substitute for answering.\n\n"
        "If the CONTEXT does not contain the answer (the question is about something outside "
        "this course/page), say you don't have that information here and tell the user to visit "
        "the relevant course or the courses page for it - don't try to answer from outside "
        "knowledge.\n\n"
        f"Reply in {lang_name} - this is the language the user has chosen for the whole session, "
        "regardless of what language the CONTEXT above happens to be written in. Never switch "
        "language to match the CONTEXT's language.\n\n"
        "Keep answers concise and friendly."
    )
    user = f"CONTEXT:\n{context}\n\nQUESTION: {question}"
    return strip_decorative_symbols(_complete(system, user))


def answer_with_context(question: str, context_chunks: list[str], language: str) -> str:
    # lru_cache needs hashable args, so tuple-ify the chunk list - the exact
    # same question against the exact same retrieved chunks (common for
    # popular FAQ-style questions) then hits the cache instead of the API.
    return _cached_answer(question, tuple(context_chunks), language)


def _word_count_of(text: str) -> int:
    return len(text.split())


def summarize(text: str, length: str, language: str, title: str | None = None,
              word_count: int | None = None) -> str:
    """Disk-cached wrapper: the same course/module (identified by its exact
    text) + length/language/title/word_count only ever hits Groq once,
    persisted across restarts - see the disk-cache block near the top of
    this file. If the underlying course text is later edited, that's a
    different `text` value, so it's a cache miss and gets summarized fresh
    automatically; the old entry just sits unused."""
    key_parts = (text, length, language, title, word_count)
    return _disk_cached("summarize", key_parts, lambda: _summarize_impl(text, length, language, title, word_count))


def _summarize_impl(text: str, length: str, language: str, title: str | None,
                     word_count: int | None) -> str:
    lang_name = _LANG_NAME.get(language, "English")
    if word_count:
        # An explicit target (e.g. "summarize in 100 words" / "summary in
        # 50 words") always wins over the generic short/long modes.
        low, high = max(5, word_count - 15), word_count + 15
        instruction = (
            f"Write a summary of EXACTLY about {word_count} words (stay within {low}-{high} words - "
            "do not go noticeably over or under). Even at this length, cover every important concept, "
            "point, and takeaway from the content - do not skip a major topic just to hit the word "
            "count; instead compress each topic to a phrase."
        )
    elif length == "short":
        low, high = 100, 150
        instruction = (
            f"Write a summary of {low}-{high} words that covers ALL the important concepts, points, "
            "and takeaways from the content - don't skip any major topic. Use short sentences or "
            "bullet points, prioritizing completeness within that word range."
        )
    else:
        low, high = 200, 300
        instruction = (
            f"Write a LONG, structured summary ({low}-{high} words) that covers every important "
            "concept in the content. Use short paragraphs or bullet points covering: what it is, "
            "who it's for, what's covered (list every major topic/module), and the outcome/benefit."
        )
    system = (
        "You are the Rozzgaar website assistant. Summarize the given page/course content "
        f"faithfully - do not invent facts, prices, or claims not present in the text. Do not be "
        f"overly brief - use the full word range you're given below. Reply in {lang_name} - this "
        "is the language the user chose for this session, regardless of what language the CONTENT "
        "below is written in. Never switch language to match the CONTENT's language."
    )
    heading = f"TITLE: {title}\n" if title else ""
    user = f"{heading}CONTENT:\n{text}\n\n{instruction}"
    # Scale the token budget for larger targets so the model isn't cut off
    # mid-summary (roughly 3 tokens/word, with headroom).
    target_words = word_count or high
    max_tokens = max(600, min(1600, target_words * 3))
    summary = _complete(system, user, temperature=0.2, max_tokens=max_tokens)

    # Models don't always hit a word target on the first try (usually by
    # coming in short). If the result falls outside the [low, high] range
    # (whether that came from an explicit word_count or the default
    # 100-150/200-300 ranges above), ask again with the actual vs. target
    # range spelled out. Capped to ONE retry (not two) - each retry resends
    # the full content plus a correction note, so every extra retry is
    # close to another full summarize call's worth of tokens; one retry
    # already fixes the vast majority of misses, and this only ever runs
    # once per unique summary now that summarize() is disk-cached above -
    # not worth 3x the tokens on every first-time summary for the last
    # few edge cases a second retry would catch.
    target_label = f"{word_count} words" if word_count else f"{low}-{high} words"
    for _ in range(1):
        actual = _word_count_of(summary)
        if low <= actual <= high:
            break
        direction = "expand" if actual < low else "shorten"
        correction = (
            f"{user}\n\nYour previous attempt was {actual} words; the target is {target_label}. "
            f"{direction.capitalize()} the summary (same content, same {lang_name}) to land within "
            f"{low}-{high} words. If expanding, add more explanation/context for the concepts already "
            "in your summary rather than repeating the same points - do not drop any important concept."
        )
        summary = _complete(system, correction, temperature=0.15, max_tokens=max_tokens)

    return strip_decorative_symbols(summary)


_TRANSLATE_CHUNK_CHARS = 4500  # Google's free web-translate endpoint (via deep-translator) rejects requests over ~5000 chars - leave headroom
_TRANSLATE_MAX_RETRIES = 3  # the free endpoint occasionally 429s/errors under concurrent load; a few retries with backoff clears almost all of these

# The free translate.google.com endpoint isn't a real API - it's Google's
# web frontend, and it starts handing back HTTP-error pages (not 429s, an
# actual "Error 500 (Server Error)!!1500..." page, caught by
# _looks_like_translate_error_page below) once enough requests land on it
# in a short window. A wide worker pool sending a whole page's worth of
# text-node chunks at once is exactly that burst pattern. Capping
# concurrency + a bit of random jitter on the retry backoff spreads the
# same requests out over time instead of firing them all at once, which
# noticeably cuts the error-page rate under real page-translate load.
_TRANSLATE_MAX_WORKERS = 4


@lru_cache(maxsize=_CACHE_MAXSIZE)
def translate(text: str, language: str) -> str:
    """Faithful translation (not a summary) - used for reading page/module
    text aloud in the requested language before it goes to TTS, and for
    individual "translate this page" DOM-node strings (see translate_batch
    below, which calls back into this same cached function per node). Goes
    through Google Translate (deep-translator, no API key) rather than an
    LLM - translation doesn't need reasoning, and this sidesteps Groq's
    rate limits and reasoning-token budget entirely. Long text is chunked
    internally (see _TRANSLATE_CHUNK_CHARS) so a full course/module reading
    isn't cut short by Google's per-request character cap - the whole
    page/module gets translated and read, not a partial excerpt."""
    if language == "en" or not text.strip():
        return strip_decorative_symbols(text)
    if len(text) <= _TRANSLATE_CHUNK_CHARS:
        return _translate_chunk(text, language)

    # Split on paragraph boundaries (course text is tagged with "\n\n## "
    # headings by the widget) and pack them into chunks up to the char
    # limit, so each request stays under Google's cap while keeping
    # headings/paragraphs intact instead of cutting mid-sentence.
    paragraphs = text.split("\n\n")
    chunks: list[str] = []
    current: list[str] = []
    current_chars = 0
    for para in paragraphs:
        para_chars = len(para)
        if current and current_chars + para_chars > _TRANSLATE_CHUNK_CHARS:
            chunks.append("\n\n".join(current))
            current, current_chars = [], 0
        current.append(para)
        current_chars += para_chars
    if current:
        chunks.append("\n\n".join(current))

    # Chunks are independent HTTP calls with no shared state, so they're
    # dispatched in parallel instead of one-at-a-time - for a long
    # module/page this is the single biggest speed win available here
    # (N chunks in ~1 chunk's latency instead of N chunks' worth).
    with ThreadPoolExecutor(max_workers=min(_TRANSLATE_MAX_WORKERS, len(chunks))) as pool:
        translated_chunks = list(pool.map(lambda c: _translate_chunk(c, language), chunks))
    return "\n\n".join(translated_chunks)


# Signatures of Google's own HTTP-error HTML page (500/503/etc). Under load
# (e.g. this batch's parallel requests, or Google's own free-endpoint
# throttling) translate.google.com can return one of these error pages
# instead of a translation - and deep-translator doesn't always recognize
# that as a failure, since the page still parses as *some* text at the DOM
# position it scrapes. Left unchecked, that error-page text gets accepted
# as a "successful" translation and shown to the user (e.g. "Error 500
# (Server Error)!!1500...") instead of the real content. Checked as a
# substring match (case-insensitive) so it still catches the page regardless
# of exact wording/formatting.
_TRANSLATE_ERROR_SIGNATURES = ("error 500", "error 503", "server error", "that's all we know")


def _looks_like_translate_error_page(s: str) -> bool:
    lowered = s.lower()
    return any(sig in lowered for sig in _TRANSLATE_ERROR_SIGNATURES)


def _backoff_with_jitter(delay: float) -> float:
    # Plain exponential backoff means every concurrently-throttled worker in
    # the pool wakes up and retries at the SAME moment, which just recreates
    # the same burst that got them throttled in the first place. Adding
    # +/-30% random jitter spreads those retries out over time instead.
    return delay * random.uniform(0.7, 1.3)


@lru_cache(maxsize=_CACHE_MAXSIZE)
def _translate_chunk(text: str, language: str) -> str:
    target = _DT_LANG.get(language, "en")
    delay = 1.0
    last_exc: Exception | None = None
    for attempt in range(_TRANSLATE_MAX_RETRIES + 1):
        try:
            translated = GoogleTranslator(source="auto", target=target).translate(text)
            if translated and _looks_like_translate_error_page(translated):
                # Not a real translation - Google's backend served an error
                # page and the library didn't raise for it. Treat exactly
                # like TooManyRequests: retry with backoff, then fail open.
                last_exc = RuntimeError("Google Translate returned an error-page response, not a translation")
                if attempt < _TRANSLATE_MAX_RETRIES:
                    sleep_for = _backoff_with_jitter(delay)
                    logger.warning("Google Translate returned an error page, retrying in %.1fs (attempt %d/%d).",
                                    sleep_for, attempt + 1, _TRANSLATE_MAX_RETRIES)
                    time.sleep(sleep_for)
                    delay *= 2
                    continue
                break
            return strip_decorative_symbols(translated or text)
        except TooManyRequests as exc:
            last_exc = exc
            if attempt < _TRANSLATE_MAX_RETRIES:
                sleep_for = _backoff_with_jitter(delay)
                logger.warning("Google Translate rate limited, retrying in %.1fs (attempt %d/%d).",
                                sleep_for, attempt + 1, _TRANSLATE_MAX_RETRIES)
                time.sleep(sleep_for)
                delay *= 2
        except (RequestError, TranslationNotFound) as exc:
            last_exc = exc
            break
        except Exception as exc:  # noqa: BLE001 - network hiccups (DNS, connection
            # reset, timeout) surface as requests' own exception types, not
            # deep_translator's; treat them the same as the named cases above -
            # fail open to the original text rather than raising out of a
            # thread-pool worker and taking down the whole batch/request.
            last_exc = exc
            break
    # Fail open: never block the page/read-aloud on a translation hiccup -
    # surface the original text rather than raising, and let the caller's
    # logs show why (translate_batch/translate.py's router log this too).
    logger.warning("Google Translate failed for a %d-char chunk (%s); returning source text untranslated.",
                    len(text), last_exc)
    return strip_decorative_symbols(text)


def translate_batch(texts: tuple[str, ...], language: str) -> list[str]:
    """Translates a list of independent text-node strings - each one exactly
    what gets swapped back into ONE DOM node in place (a heading, a button
    label, a paragraph, a link) - for the "translate this page" feature.
    Unlike the days when this batched many nodes into one Groq/JSON call,
    each node now goes through translate() (Google Translate, no LLM) on
    its own - so there's no shared-batch JSON to parse or mis-align, and a
    failure on one node (see _translate_chunk's fail-open above) can never
    corrupt or shift any other node's result. Must return a list the same
    length, in the same order, as `texts`, since the caller maps result[i]
    straight onto the DOM node that produced texts[i]."""
    if not texts:
        return []
    if language == "en":
        return [strip_decorative_symbols(t) for t in texts]

    # Items that are blank (or already have no translatable letters, e.g.
    # "$99", "->") don't need a network call at all - skip them here.
    indices_to_translate = [i for i, t in enumerate(texts) if t and t.strip()]
    results: list[str] = list(texts)
    if not indices_to_translate:
        return results

    def run_one(i: int) -> None:
        results[i] = translate(texts[i], language)

    # Each node is its own quick HTTP call (not one big prompt), so in
    # principle a wide pool is fine here (this used to be capped at 4 to
    # stay polite to Groq's per-minute LLM limit, which no longer applies
    # now that translation goes through Google Translate instead). In
    # practice though, a page walk can produce a couple hundred nodes, and
    # firing 8-at-a-time at Google's free translate endpoint is exactly the
    # burst pattern that gets it to start handing back error pages instead
    # of translations (see _TRANSLATE_MAX_WORKERS above) - capped to the
    # same value used for internal chunking so the whole pipeline applies
    # one consistent concurrency limit.
    with ThreadPoolExecutor(max_workers=_TRANSLATE_MAX_WORKERS) as pool:
        list(pool.map(run_one, indices_to_translate))

    return results


def generate_suggested_questions(context_text: str, language: str, count: int = 5) -> list[dict]:
    """Disk-cached wrapper - see summarize() above for why. Same
    context_text + language + count only ever hits Groq once, persisted
    across restarts, and stays correct automatically if context_text
    changes (different key -> regenerated fresh)."""
    key_parts = (context_text, language, count)
    return _disk_cached("suggested_questions", key_parts,
                         lambda: _generate_suggested_questions_impl(context_text, language, count))


def _generate_suggested_questions_impl(context_text: str, language: str, count: int) -> list[dict]:
    lang_name = _LANG_NAME.get(language, "English")
    system = (
        "You are the Rozzgaar website assistant. Based on the given content, propose sample "
        "questions a prospective student might ask, with short accurate answers grounded only "
        f"in the content. Reply in {lang_name} - this is the language the user chose for this "
        "session, regardless of what language the CONTENT below is written in. Never switch "
        "language to match the CONTENT's language. Do not use emoji or decorative symbols/icons "
        "anywhere in the question or answer text - these are read aloud by text-to-speech. "
        "Respond with ONLY a JSON array, no markdown, no commentary, in this exact shape: "
        '[{"question": "...", "answer": "..."}]'
    )
    user = f"CONTENT:\n{context_text}\n\nGenerate exactly {count} question/answer pairs."
    raw = _complete(system, user, temperature=0.4, max_tokens=800)
    qa = _safe_parse_qa(raw)
    return [
        {"question": strip_decorative_symbols(item["question"]), "answer": strip_decorative_symbols(item["answer"])}
        for item in qa
    ]


def _safe_parse_qa(raw: str) -> list[dict]:
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        cleaned = cleaned.replace("json\n", "", 1) if cleaned.startswith("json\n") else cleaned
    try:
        data = json.loads(cleaned)
        if isinstance(data, list):
            return [
                {"question": item.get("question", "").strip(), "answer": item.get("answer", "").strip()}
                for item in data if isinstance(item, dict)
            ]
    except (json.JSONDecodeError, AttributeError) as exc:
        logger.warning("Failed to parse suggested-questions JSON: %s | raw=%s", exc, raw[:200])
    return []